---
- name: Remove user from developer group - (remove ability to create projects)
  command: "oc adm groups remove-users {{ item }} {{ ocp_username }}"
  register: groupadd_register
  with_items: "{{ ocp_user_groups }}"
  when:
    - ocp_username is defined
    - ocp_user_groups | default([]) | length > 0

- name: Remove ClusterResourceQuota  "clusterquota-{{ ocp_username }}-{{ guid }}"
  k8s:
    username: system:admin
    state: absent
    api_version: quota.openshift.io/v1
    kind: ClusterResourceQuota
    name: "clusterquota-{{ ocp_username }}-{{ guid }}"

- name: Find all projects
  k8s_facts:
    username: system:admin
    api_version: project.openshift.io/v1
    kind: Project
  register: r_projects

- name: Remove Projects for user {{ ocp_username }} -  Debug statement
  debug:
    msg: "Found user project: {{ item.metadata.name }}"
    verbosity: 1
  when:
  - item.metadata.annotations['openshift.io/requester'] is defined
  - item.metadata.annotations['openshift.io/requester'] == ocp_username
  loop: "{{ r_projects.resources }}"

- name: Remove Projects for user {{ ocp_username }}
  k8s:
    username: system:admin
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ item.metadata.name }}"
  when:
  - item.metadata.annotations['openshift.io/requester'] is defined
  - item.metadata.annotations['openshift.io/requester'] == ocp_username
  - item.status.phase is defined
  - item.status.phase != "Terminating"
  loop: "{{ r_projects.resources }}"

- name: Remove user from Grading Jenkins"
  ignore_errors: true
  command: |
    oc policy remove-role-from-user view {{ocp_username}} -n {{gpte_jenkins_project}}

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
