---
- environment:
    AWS_PROFILE: "{{ account_name }}"
    AWS_REGION: "{{ _region }}"
  ignore_errors: yes
  block:
    - name: Get all security groups
      register: r_all_sg
      ec2_group_facts:

    - when: r_all_sg.security_groups | length > 0
      block:
        - name: Clean up all ingress and egress rules
          loop: "{{ r_all_sg.security_groups }}"
          loop_control:
            loop_var: _sg
          ec2_group:
            rules: []
            rules_egress: []
            name: "{{ _sg.group_name }}"
            description: "{{ _sg.description }}"
            vpc_id: "{{ _sg.vpc_id }}"

        - set_fact:
            run_aws_nuke_again: true
